name: urdf-lite-env
channels:
  - conda-forge
  - emscripten-forge
dependencies:
  - xeus-python 
  - jupyterlab_widgets >=3.0
  - ipywidgets >=8.0
  - pip:
    - ./jupyterlab_urdf-0.6.0-py3-none-any.whl
